title: I Live Here Now
author: J Kalmbach
email: jikalmbach@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  German speaking, Norwegian speaking, English speaking, html, css, vanilla javascript, learning always, nerd. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: MegaNerdGirl # DO NOT include the @ character, or else the build will fail!
github_username:  JKalmbach # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
